<?php
namespace AvatarPlus\CacheTest;
use AvatarPlus\Cache\Cache as Cache;

//require_once 'bootstrap.php';
require_once PLUGIN_BASE_PATH . '/avatarplus.php';
require_once PLUGIN_BASE_PATH . '/classes/class-cache.php';

// init autoloader
\AvatarPlus\init_autoloader();

/**
 * Test class for Cache.
 * Generated by PHPUnit on 2013-02-09 at 13:19:08.
 */
class CacheTest extends \WP_UnitTestCase
{
    /**
     * @var Cache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->object = new Cache( 1 );
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
    }

    public function UrlObject_DataProvider() {
    	return array(
    		array(
		    	array(
		    		'url'        => 'http://wordpress.org',
		    		'location'   => '',
		    		'service'    => 'unknown',
		    		'avatar_url' => ''
		    	),
    			false
    		),

    		array(
		    	array(
		    		'url'        => 'https://plus.google.com/116844107236111670286',
		    		'location'   => 'https://plus.google.com/116844107236111670286',
		    		'service'    => 'googleplus',
		    		'avatar_url' => 'https://lh3.googleusercontent.com/-lfNe944BTaQ/AAAAAAAAAAI/AAAAAAAAASs/qTpT5xts0L0/photo.jpg?sz=44'
		    	),
    			true
    		),

    		array(
		    	array(
		     		'url'        => 'http://neun12.de/+',
		    		'location'   => 'https://plus.google.com/116844107236111670286',
		    		'service'    => 'googleplus',
		    		'avatar_url' => 'https://lh3.googleusercontent.com/-lfNe944BTaQ/AAAAAAAAAAI/AAAAAAAAASs/qTpT5xts0L0/photo.jpg?sz=44'
		    	),
    			true
    		),

   			array(
   					array(
   							'url'        => 'https://www.facebook.com/OoroonBai',
   							'location'   => 'https://www.facebook.com/OoroonBai',
   							'service'    => 'facebook',
   							'avatar_url' => 'http://profile.ak.fbcdn.net/hprofile-ak-snc7/370016_100002361552122_1339166872_q.jpg'
   					),
   					true
   			),

    		array(
   					array(
   							'url'        => 'http://neun12.de/fb',
   							'location'   => 'https://www.facebook.com/OoroonBai',
   							'service'    => 'facebook',
   							'avatar_url' => 'http://profile.ak.fbcdn.net/hprofile-ak-snc7/370016_100002361552122_1339166872_q.jpg'
   					),
   					true
   			),

    		array(
   					array(
   							'url'        => 'https://www.twitter.com/OoroonBai',
   							'location'   => 'https://www.twitter.com/OoroonBai',
   							'service'    => 'twitter',
   							'avatar_url' => 'https://si0.twimg.com/profile_images/129274816/dot3_normal.gif'
   					),
   					true
   			)

    	);
    }

    public function Url_DataProvider() {
    	return array(
    		array( 'neun12@gmail.com', false ),
    		array( 'https://plus.google.com/116844107236111670286', true ),
    		array( 'http://neun12.de/+', true ),
    		array( 'https://www.facebook.com/OoroonBai', true ),
    		array( 'http://neun12.de/fb', true ),
    		array( 'https://twitter.com/OoroonBai', true )
    	);
    }

    public function CachedUrl_DataProvider() {
    	return array(
    		array( 'neun12@gmail.com', null ),
    		array( 'https://plus.google.com/116844107236111670286', 'https://plus.google.com/116844107236111670286' ),
    		array( 'http://neun12.de/+', 'http://neun12.de/+' ),
    		array( 'https://www.facebook.com/OoroonBai', 'https://www.facebook.com/OoroonBai' ),
    		array( 'http://neun12.de/fb', 'http://neun12.de/fb' ),
    		array( 'https://twitter.com/OoroonBai', 'https://twitter.com/OoroonBai' )
    	);
    }

    public function testIsCacheNotEmpty() {

    	$cache = &$this->object;
    	$this->assertFalse( empty( $cache::$cache ) );

    }

    /**
     * @covers AvatarPlus\Cache\Cache::is_cached
     * @dataProvider Url_DataProvider
     */
    public function testIs_cached( $url, $expected ) {

    	$cached = $this->object->is_cached( $url );
    	$this->assertEquals( $cached, $expected );

    }

    /**
     * @covers AvatarPlus\Cache\Cache::get_cached_url
     * @dataProvider CachedUrl_DataProvider
     */
    public function testGet_cached_url( $url, $expected ) {

    	$url_object = $this->object->get_cached_url( $url );

    	if( ! is_object( $url_object ) )
    		$this->assertEquals( $expected, $url_object );
    	else
    		$this->assertEquals( $expected, $url_object->url );

    }

    /**
     * @covers AvatarPlus\Cache\Cache::cache_url
     * @dataProvider UrlObject_DataProvider
     */
    public function testCache_url( $url, $expected ) {

    	$cache = &$this->object;
    	$cache->reset_cache( 1 );

    	$urldata = (object) $url;

    	$new_cache = $cache->cache_url( $urldata );

    	$result = isset( $new_cache[ md5( $urldata->url ) ] );

    	$this->assertEquals( $expected, $result );

    }

    /**
     * @covers AvatarPlus\Cache\Cache::read_cache
     * @todo Implement testRead_cache().
     */
    public function testRead_cache()
    {
    }

    /**
     * @covers AvatarPlus\Cache\Cache::write_cache
     * @todo Implement testWrite_cache().
     */
    public function testWrite_cache()
    {
    }
}
?>
