<?php
namespace AvatarPlus\Backend;


require_once 'D:\htdocs\wp300\wp-content\plugins\avatar-plus\classes\class-backend.php';

/**
 * Test class for Backend.
 * Generated by PHPUnit on 2013-01-14 at 04:20:15.
 */
class BackendTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Backend
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Backend;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AvatarPlus\Backend\Backend::get_option
     * @todo Implement testGet_option().
     */
    public function testGet_option()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::init_translation
     * @todo Implement testInit_translation().
     */
    public function testInit_translation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::settings_api_init
     * @todo Implement testSettings_api_init().
     */
    public function testSettings_api_init()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::add_menu_page
     * @todo Implement testAdd_menu_page().
     */
    public function testAdd_menu_page()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::add_help_tab
     * @todo Implement testAdd_help_tab().
     */
    public function testAdd_help_tab()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::options_validate
     * @todo Implement testOptions_validate().
     */
    public function testOptions_validate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::get_text
     * @todo Implement testGet_text().
     */
    public function testGet_text()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::main_section
     * @todo Implement testMain_section().
     */
    public function testMain_section()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::aplus_section
     * @todo Implement testAplus_section().
     */
    public function testAplus_section()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::comment_field
     * @todo Implement testComment_field().
     */
    public function testComment_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::cache_field
     * @todo Implement testCache_field().
     */
    public function testCache_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::gplus_section
     * @todo Implement testGplus_section().
     */
    public function testGplus_section()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AvatarPlus\Backend\Backend::gplus_field
     * @todo Implement testGplus_field().
     */
    public function testGplus_field()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
